---
# vim: set ft=ansible:

- hosts: localhost
  connection: local

  tasks:
    - name: New GPT partition table
      parted:
        device: /dev/sda
        label: gpt
        state: present

    - name: Add boot partition
      parted:
        device: /dev/sda
        name: boot
        number: 1
        part_type: primary
        part_start: "0%"
        part_end: "256MiB"
        unit: "MiB"
        flags: [ boot, esp ]
        state: present

    - name: Add root partition
      parted:
        device: /dev/sda
        name: boot
        number: 2
        part_type: primary
        part_start: "257MiB"
        part_end: "113664MiB"
        unit: "MiB"
        state: present

    - name: Add swap partition
      parted:
        device: /dev/sda
        name: boot
        number: 3
        part_type: primary
        part_start: "113665MiB"
        part_end: "100%"
        unit: "MiB"
