---
# vim: set ft=ansible:

- hosts: localhost
  connection: local

  tasks:
    - name: Partition the disks
      parted:
        device: /dev/sda
        name: "{{ item.name | default(omit) }}"
        label: gpt
        number: "{{ item.number }}"
        part_type: "{{ item.part_type }}"
        part_start: "{{ item.part_start }}"
        part_end: "{{ item.part_end }}"
        unit: "{{ item.unit }}"
        flags: "{{ item.flags | default(omit) }}"
        state: present
      with_items:
        - name: boot
          number: 1
          type: primary
          part_start: "0%"
          parte_end: "256MiB"
          unit: "MiB"
          flags: "boot, esp"
        - name: root
          number: 2
          type: primary
          part_start: "257MiB"
          parte_end: "122112MiB"
          unit: "MiB"
        - name: swap
          number: 3
          type: primary
          part_start: "122113MiB"
          parte_end: "100%"
          unit: "MiB"
